INSERT INTO items (seller_id,title, description, price, type, size, status, condition, city)
VALUES
  (1, 'Stealthy Trailblazer', 'Unleash your inner adventurer with this high-performance mountain bike. Conquer rugged trails, tackle challenging terrain, and experience the thrill of off-road exploration.', 1200.00, 'Mountain', 'M', 'Available', 'New', 'Vancouver'),
  (2, 'Speed Demon Roadster', 'Get ready to experience the exhilaration of speed on the open road with the Speed Demon Roadster. Designed for road warriors and cycling enthusiasts, this sleek and aerodynamic road bike offers unmatched performance, precision, and control.', 1500.00, 'Road', 'L', 'Available', 'Like New', 'Toronto'),
  (3, 'Urban Explorer Hybrid', 'Navigate city streets and rugged trails with confidence on the Urban Explorer Hybrid. Seamlessly transition from urban commutes to weekend adventures, enjoying the versatility and comfort of this hybrid bike. Its lightweight frame, responsive handling, and stylish design make it the ideal choice for modern explorers.', 800.00, 'Hybrid', 'S', 'Available', 'Used', 'Montreal'),
  (4, 'Off-Road Maverick', 'Experience the thrill of off-road adventures with the Off-Road Maverick. Designed to tackle challenging trails and rocky terrains, this mountain bike boasts exceptional durability and performance. The Maverick''s advanced suspension system and responsive components ensure a smooth and exhilarating ride every time.', 900.00, 'Mountain', 'L', 'Available', 'Used', 'Calgary'),
  (5, 'Electric Commuter Companion', 'Elevate your daily commute with the Electric Commuter Companion. Effortlessly navigate city streets, conquer hills, and breeze through traffic using the powerful electric motor. With its stylish design, long-lasting battery, and advanced features, this e-bike transforms your daily routine into a delightful adventure.', 1800.00, 'Electric', 'M', 'Available', 'Like New', 'Edmonton'),
  (6, 'Cityscape Cruiser', 'Cruise through the city in style and comfort with the Cityscape Cruiser. Designed for urban dwellers and leisurely riders, this hybrid city bike offers a relaxed and upright riding position. Glide along streets, parks, and pathways while enjoying the smooth ride and timeless design of the Cityscape Cruiser.', 600.00, 'Hybrid', 'M', 'Available', 'Used', 'Ottawa'),
  (1, 'Trailblazing Warrior', 'Unleash your inner trailblazer with the Trailblazing Warrior. Built to conquer rugged terrain and overcome obstacles, this mountain bike offers robust performance and versatility. Whether you''re tackling technical trails or exploring scenic routes, the Trailblazing Warrior is your ultimate companion.', 1100.00, 'Mountain', 'L', 'Available', 'Used', 'Winnipeg'),
  (2, 'Aerodynamic Road Ace', 'Transform your road cycling experience with the Aerodynamic Road Ace. Engineered for speed and efficiency, this road bike delivers unparalleled aerodynamics and precision handling. Reach new levels of performance as you slice through the wind and set new personal records.', 1700.00, 'Road', 'M', 'Available', 'New', 'Halifax'),
  (3, 'Urban Commuter Companion', 'Navigate the urban jungle with confidence using the Urban Commuter Companion. Whether you''re commuting to work, running errands, or exploring the city, this versatile hybrid bike offers a smooth and comfortable ride. Experience the freedom of urban cycling like never before.', 750.00, 'Hybrid', 'L', 'Available', 'Like New', 'Quebec City'),
  (4, 'Electrifying Adventure', 'Embark on electrifying adventures with the powerful Electrifying Adventure e-bike. Conquer challenging terrains, climb steep hills, and extend your range with ease. This electric bike combines cutting-edge technology with thrilling performance to elevate your outdoor escapades.', 2200.00, 'Electric', 'M', 'Available', 'New', 'Victoria'),
  (5, 'Mountain Majesty', 'Experience the majesty of the mountains with the Mountain Majesty trail bike. Designed for thrill-seekers and nature enthusiasts, this full-suspension mountain bike offers exceptional control, stability, and agility on rugged trails. Elevate your mountain biking game and chase the thrill of adventure.', 1350.00, 'Mountain', 'L', 'Available', 'Used', 'Saskatoon'),
  (6, 'Sleek Speedster', 'Unleash your inner speedster with the Sleek Speedster aerodynamic road bike. Designed for those who crave speed and performance, this road bike combines cutting-edge technology with sleek aesthetics. Whether you''re racing or embarking on long-distance journeys, the Sleek Speedster is your ticket to cycling excellence.', 1900.00, 'Road', 'L', 'Available', 'Like New', 'Regina');
